# ========================= 
# Credit Card Fraud Detection Project Config 
# =========================

project:
  name: Credit Card Fraud Detection
  version: 1.0.0
  description: A project to detect fraudulent credit card transactions using machine learning.
  mode: batch

paths:
  data_raw: "data/raw/creditcard.csv"
  data_processed: "data/processed/feature_engineered_data.csv"
  data_external: "data/external/external_data.csv"
  data_external_process: "data/external/processed/external_processed_data.csv"
  data_interim: "data/interim/processed_data.csv"
  models: "models"

model:
  type: xgboost # Options: xgboost, random_forest, logistic_regression

training:
  train_size: 0.8
  batch_size: 64
  epochs: 50
  learning_rate: 0.001
  optimizer: "adam"
  loss_function: "binary_crossentropy"
  validation_split: 0.2
  random_seed: 42
  calibrate_model: false
  early_stopping: 
    enabled: true
    patience: 5


evaluation:
  metrics: [precision, recall, f1, roc_auc, average_precision_score]
  threshold: 0.5

serving:
  api_host: "0.0.0.0"
  api_port: 8000
  model_file: "models/fraudulent_model.pkl"